### ISSUE TITLE
Get website ready for ECMS night

### ISSUE THREAD

**Issue by JJ11teen** [adelaideblockchain/adelaideblockchain.github.io#1]
* Remove extraneous pages
* Remove calendar
* Insert Content
* Add mailchimp plugin

**Comment by JJ11teen** [comment]
@adelaideblockchain/project-management to create mailchimp account

**Comment by JJ11teen** [comment]
@ivanzinho09 to remove calendar and extra pages
@paulpounendis to provide additional content

**Comment by paulpounendis** [comment]
Ok so I have now created a Mail Chimp account and created two lists for Adelaide Blockchain. A Team List and a Member list. I have completed the signup form for the Member List, which is the link here     >> http://eepurl.com/dto-ub Try it out, and tell me how it works!

**Comment by paulpounendis** [comment]
Once we sort out the site I'll organise the plug in for the sign up form :)
